services:
  db:
    image: postgres:17-alpine
    container_name: humanized_bot_db
    restart: always
    environment:
      POSTGRES_USER: humanized_user
      POSTGRES_PASSWORD: humanized_password
      POSTGRES_DB: humanized_bot_engine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: node:24-alpine
    container_name: humanized_bot_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://humanized_user:humanized_password@db:5432/humanized_bot_engine?schema=public
    depends_on:
      - db

volumes:
  postgres_data:
