services:
  database:
    image: postgres:17-alpine
    container_name: humanized_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: humanized_bot
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default

volumes:
  pgdata:

networks:
  default:
    driver: bridge
